### ISSUE TITLE
What hostname do you expect?

### ISSUE THREAD

**Issue by dnephin** [Jewelbots/arm-flex-license-server#1]
```
$ cat docker-compose.yml
license-server:
  build: .
  container_name: license-server
  hostname: jwb
  mac_address: 02:31:AB:DD:19:82
  expose:
   - "8224"

$ cat Dockerfile
FROM alpine:edge
CMD hostname

$ docker-compose-1.5.1 up
Creating license-server
Attaching to license-server
license-server | jwb
license-server exited with code 0
Gracefully stopping... (press Ctrl+C again to force)

```

Seems to work for me, I expected the hostname to be `jwb`. Is that not what you expect, or is that not the result you see?

**Comment by gortok** [comment]
@dnephin Thanks for looking into this.  Last night I was getting the auto-generated hostname; as if docker-compose didn't work.

After nuking all containers and images and re-pulling; it worked. I'm not sure what happened; I'm guessing maybe it cached an image and kept using that even though it shouldn't have? I don't really know (I'm still a novice with Docker).

**Comment by dnephin** [comment]
If you see the text "Starting ..." instead of "Creating ..." or "Recreating ..." from docker-compose, then it would be using an existing container, although changes to the hostname should force a recreate

**Comment by gortok** [comment]
@dnephin Thanks for taking a look into this; it was driving me bonkers. If I can ever reproduce the 'bad', I'll put together a proper bug report for it. It genuinely shocked me that it didn't work for hours yesterday, and as soon as I nuked everything and started again (with same code), it worked.  I don't know what happened, but I'll keep an eye out.
